#!/bin/bash
#SBATCH --partition=vgpu
#SBATCH --gres=gpu:1

module load cuda/11.4

eval "$(conda shell.bash hook)"
conda activate dqn-pong
cd ~/workspace/comp3702/dqn-pong
export PYTHONPATH=$PWD

timestamp=$(date +"%Y%m%d%H%M%S")

mkdir -p log

python dqn_pong.py -e Breakout-v4 > log/$timestamp.log